### ISSUE TITLE
v7.0.0 Release Plan 

### ISSUE THREAD

**Issue by fedeci** [express-validator/express-validator#990]
This is a release plan of the next major release of `express-validator`.
## Potentially breaking bug fixes 
- [x] Passing an Array to `toString()` should not return just the first item #791, #755, #704 (PR: #1002)
- [ ] Improve `oneOf`:
  - [x] Error messages #956 (PR: #1022)
  - [ ] Wildcards #950

## New features
- [x] Pluggable validators #1077 (PR: #1079)
- [ ] Custom validators: 
  - [ ] Multiple error messages #951 
- [ ] Allow to bail out on the first element failing when using `bail()` with wildcards #906 

## Others
- [x] Remove deprecated APIs (filter, old-check, sanitize) (PR: #993)

I selected just some of the most recent and requested features/fixes, but this list is supposed to change so proposals are welcome!

/cc @gustavohenke Can you create a branch (`v7.0.0-features`?) on this repo to use as the base for PRs? When we merge it we should use `Rebase and merge` instead of `Squash and merge` so that we can track of those breaking commits better. It would definitely simplify development.

**Comment by gustavohenke** [comment]
There you go for the branch: https://github.com/express-validator/express-validator/tree/v7-features
I suppose also change the base of #993?

Without thinking too much about the proposed features and breaking changes, what I can say at the moment is... yeah, let's definitely change the behaviour of `toString`.

Thanks for organising all of this!

**Comment by olawalejuwonm** [comment]
Please let matchedData(req[, options]) retuen location of the data matched please

**Comment by gugu** [comment]
You could add an option to change this behaviour in v6. Something like
```
import {setArrayStrictMode} from "express-validator";
setArrayStrictMode(true);
```

so people don't need to wait for v7

**Comment by fedeci** [comment]
Haven't I backported it?

**Comment by gugu** [comment]
https://stackblitz.com/edit/node-dbzm28?file=index.js

Not in the latest version. Visiting https://node-dbzm28--3000.local.webcontainer.io?s=aaa@test.com&s=bbb@test.com returns:
`validation passed for:{"s":["aaa@test.com","bbb@test.com"]}`

**Comment by gugu** [comment]
@fedeci is me minimal reproduceable example correct?

**Comment by fedeci** [comment]
I'll see how I can backport it!Eventually we can release beta versions containing stable changes for v7.
